#ifndef BLHELI_S_PARAMETER_LAYOUT_H
#define BLHELI_S_PARAMETER_LAYOUT_H

#include <stdint.h>

#define BLHELI_S_PARAMETER_LAYOUT_REVISION UINT8_C(33)
#define BLHELI_S_PARAMETER_SIGNATURE_LOW UINT8_C(0x55)
#define BLHELI_S_PARAMETER_SIGNATURE_HIGH UINT8_C(0xaa)
#define BLHELI_S_PARAMETER_PLACEHOLDER UINT8_C(0xff)
#define BLHELI_S_PARAMETER_RECORD_SIZE UINT8_C(58)
#define BLHELI_S_PARAMETER_NAME_OFFSET UINT8_C(42)
#define BLHELI_S_PARAMETER_NAME_LENGTH UINT8_C(16)

#define BLHELI_S_PARAMETER_OFFSET_FW_MAIN UINT8_C(0)
#define BLHELI_S_PARAMETER_OFFSET_FW_SUB UINT8_C(1)
#define BLHELI_S_PARAMETER_OFFSET_LAYOUT_REVISION UINT8_C(2)
#define BLHELI_S_PARAMETER_OFFSET_STARTUP_POWER UINT8_C(8)
#define BLHELI_S_PARAMETER_OFFSET_DIRECTION UINT8_C(10)
#define BLHELI_S_PARAMETER_OFFSET_SIGNATURE_LOW UINT8_C(13)
#define BLHELI_S_PARAMETER_OFFSET_SIGNATURE_HIGH UINT8_C(14)
#define BLHELI_S_PARAMETER_OFFSET_ENABLE_TX_PROGRAMMING UINT8_C(15)
#define BLHELI_S_PARAMETER_OFFSET_COMMUTATION_TIMING UINT8_C(21)
#define BLHELI_S_PARAMETER_OFFSET_MIN_THROTTLE UINT8_C(25)
#define BLHELI_S_PARAMETER_OFFSET_MAX_THROTTLE UINT8_C(26)
#define BLHELI_S_PARAMETER_OFFSET_BEEP_STRENGTH UINT8_C(27)
#define BLHELI_S_PARAMETER_OFFSET_BEACON_STRENGTH UINT8_C(28)
#define BLHELI_S_PARAMETER_OFFSET_BEACON_DELAY UINT8_C(29)
#define BLHELI_S_PARAMETER_OFFSET_DEMAG_COMPENSATION UINT8_C(31)
#define BLHELI_S_PARAMETER_OFFSET_CENTER_THROTTLE UINT8_C(33)
#define BLHELI_S_PARAMETER_OFFSET_TEMPERATURE_PROTECTION UINT8_C(35)
#define BLHELI_S_PARAMETER_OFFSET_POWER_PROTECTION UINT8_C(36)
#define BLHELI_S_PARAMETER_OFFSET_BRAKE_ON_STOP UINT8_C(39)
#define BLHELI_S_PARAMETER_OFFSET_LED_CONTROL UINT8_C(40)

struct blheli_s_parameter_header {
    uint8_t firmware_main_revision;
    uint8_t firmware_sub_revision;
    uint8_t layout_revision;
    uint8_t initialized_signature_low;
    uint8_t initialized_signature_high;
};

#endif
